import type { Metadata } from "next";
import "./globals.css";
import AppNavbar from "@/components/AppNavbar";
import AppFooter from "@/components/AppFooter";
import { AuthProvider } from "@/hooks/use-auth";
import LoadingLayout from "@/components/LoadingLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <LoadingLayout>
            <AppNavbar />
            <main className="min-h-[calc(100vh-56px)]">
              {children}
            </main>
            <AppFooter />
          </LoadingLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
